// Code generated by protoc-gen-gogo.
// source: bezos.proto
// DO NOT EDIT!

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	bezos.proto
	cats.proto
	checker.proto
	keelhaul.proto
	spanx.proto
	vape.proto

It has these top-level messages:
	BezosRequest
	ListChecksRequest
	ListChecksResponse
	CheckResourceResponse
	ResourceResponse
	CheckResourceRequest
	ResultsResource
	TestCheckRequest
	TestCheckResponse
	ListBastionStatesRequest
	ListBastionStatesResponse
	ScanVpcsRequest
	ScanVpcsResponse
	LaunchStackRequest
	LaunchStackResponse
	AuthenticateBastionRequest
	AuthenticateBastionResponse
	PutRoleRequest
	PutRoleResponse
	GetCredentialsRequest
	GetCredentialsResponse
	GetUserRequest
	GetUserResponse
	ListUsersRequest
	ListUsersResponse
	ListCustomersResponse
*/
package service

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/opsee/protobuf/opseeproto"
import _ "github.com/opsee/protobuf/opseeproto/types"
import opsee_aws_cloudwatch "github.com/opsee/basic/schema/aws/cloudwatch"
import opsee_aws_ec2 "github.com/opsee/basic/schema/aws/ec2"
import opsee_aws_elb "github.com/opsee/basic/schema/aws/elb"
import opsee_aws_autoscaling "github.com/opsee/basic/schema/aws/autoscaling"
import opsee_aws_rds "github.com/opsee/basic/schema/aws/rds"
import opsee1 "github.com/opsee/basic/schema"

import github_com_graphql_go_graphql "github.com/graphql-go/graphql"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type BezosRequest struct {
	User *opsee1.User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	// Types that are valid to be assigned to Input:
	//	*BezosRequest_Cloudwatch_ListMetricsInput
	//	*BezosRequest_Cloudwatch_GetMetricsStatisticsInput
	//	*BezosRequest_Ec2_DescribeInstancesInput
	//	*BezosRequest_Ec2_DescribeSecurityGroupsInput
	//	*BezosRequest_Ec2_DescribeSubnetsInput
	//	*BezosRequest_Ec2_DescribeVpcsInput
	//	*BezosRequest_Ec2_DescribeRouteTablesInput
	//	*BezosRequest_Elb_DescribeLoadBalancersInput
	//	*BezosRequest_Autoscaling_DescribeAutoScalingGroupsInput
	//	*BezosRequest_Rds_DescribeDBInstancesInput
	Input isBezosRequest_Input `protobuf_oneof:"input"`
}

func (m *BezosRequest) Reset()         { *m = BezosRequest{} }
func (m *BezosRequest) String() string { return proto.CompactTextString(m) }
func (*BezosRequest) ProtoMessage()    {}

type isBezosRequest_Input interface {
	isBezosRequest_Input()
	Equal(interface{}) bool
}

type BezosRequest_Cloudwatch_ListMetricsInput struct {
	Cloudwatch_ListMetricsInput *opsee_aws_cloudwatch.ListMetricsInput `protobuf:"bytes,101,opt,name=cloudwatch_ListMetricsInput,oneof"`
}
type BezosRequest_Cloudwatch_GetMetricsStatisticsInput struct {
	Cloudwatch_GetMetricsStatisticsInput *opsee_aws_cloudwatch.GetMetricStatisticsInput `protobuf:"bytes,102,opt,name=cloudwatch_GetMetricsStatisticsInput,oneof"`
}
type BezosRequest_Ec2_DescribeInstancesInput struct {
	Ec2_DescribeInstancesInput *opsee_aws_ec2.DescribeInstancesInput `protobuf:"bytes,201,opt,name=ec2_DescribeInstancesInput,oneof"`
}
type BezosRequest_Ec2_DescribeSecurityGroupsInput struct {
	Ec2_DescribeSecurityGroupsInput *opsee_aws_ec2.DescribeSecurityGroupsInput `protobuf:"bytes,202,opt,name=ec2_DescribeSecurityGroupsInput,oneof"`
}
type BezosRequest_Ec2_DescribeSubnetsInput struct {
	Ec2_DescribeSubnetsInput *opsee_aws_ec2.DescribeSubnetsInput `protobuf:"bytes,203,opt,name=ec2_DescribeSubnetsInput,oneof"`
}
type BezosRequest_Ec2_DescribeVpcsInput struct {
	Ec2_DescribeVpcsInput *opsee_aws_ec2.DescribeVpcsInput `protobuf:"bytes,204,opt,name=ec2_DescribeVpcsInput,oneof"`
}
type BezosRequest_Ec2_DescribeRouteTablesInput struct {
	Ec2_DescribeRouteTablesInput *opsee_aws_ec2.DescribeRouteTablesInput `protobuf:"bytes,205,opt,name=ec2_DescribeRouteTablesInput,oneof"`
}
type BezosRequest_Elb_DescribeLoadBalancersInput struct {
	Elb_DescribeLoadBalancersInput *opsee_aws_elb.DescribeLoadBalancersInput `protobuf:"bytes,301,opt,name=elb_DescribeLoadBalancersInput,oneof"`
}
type BezosRequest_Autoscaling_DescribeAutoScalingGroupsInput struct {
	Autoscaling_DescribeAutoScalingGroupsInput *opsee_aws_autoscaling.DescribeAutoScalingGroupsInput `protobuf:"bytes,401,opt,name=autoscaling_DescribeAutoScalingGroupsInput,oneof"`
}
type BezosRequest_Rds_DescribeDBInstancesInput struct {
	Rds_DescribeDBInstancesInput *opsee_aws_rds.DescribeDBInstancesInput `protobuf:"bytes,501,opt,name=rds_DescribeDBInstancesInput,oneof"`
}

func (*BezosRequest_Cloudwatch_ListMetricsInput) isBezosRequest_Input()                {}
func (*BezosRequest_Cloudwatch_GetMetricsStatisticsInput) isBezosRequest_Input()       {}
func (*BezosRequest_Ec2_DescribeInstancesInput) isBezosRequest_Input()                 {}
func (*BezosRequest_Ec2_DescribeSecurityGroupsInput) isBezosRequest_Input()            {}
func (*BezosRequest_Ec2_DescribeSubnetsInput) isBezosRequest_Input()                   {}
func (*BezosRequest_Ec2_DescribeVpcsInput) isBezosRequest_Input()                      {}
func (*BezosRequest_Ec2_DescribeRouteTablesInput) isBezosRequest_Input()               {}
func (*BezosRequest_Elb_DescribeLoadBalancersInput) isBezosRequest_Input()             {}
func (*BezosRequest_Autoscaling_DescribeAutoScalingGroupsInput) isBezosRequest_Input() {}
func (*BezosRequest_Rds_DescribeDBInstancesInput) isBezosRequest_Input()               {}

func (m *BezosRequest) GetInput() isBezosRequest_Input {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *BezosRequest) GetUser() *opsee1.User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *BezosRequest) GetCloudwatch_ListMetricsInput() *opsee_aws_cloudwatch.ListMetricsInput {
	if x, ok := m.GetInput().(*BezosRequest_Cloudwatch_ListMetricsInput); ok {
		return x.Cloudwatch_ListMetricsInput
	}
	return nil
}

func (m *BezosRequest) GetCloudwatch_GetMetricsStatisticsInput() *opsee_aws_cloudwatch.GetMetricStatisticsInput {
	if x, ok := m.GetInput().(*BezosRequest_Cloudwatch_GetMetricsStatisticsInput); ok {
		return x.Cloudwatch_GetMetricsStatisticsInput
	}
	return nil
}

func (m *BezosRequest) GetEc2_DescribeInstancesInput() *opsee_aws_ec2.DescribeInstancesInput {
	if x, ok := m.GetInput().(*BezosRequest_Ec2_DescribeInstancesInput); ok {
		return x.Ec2_DescribeInstancesInput
	}
	return nil
}

func (m *BezosRequest) GetEc2_DescribeSecurityGroupsInput() *opsee_aws_ec2.DescribeSecurityGroupsInput {
	if x, ok := m.GetInput().(*BezosRequest_Ec2_DescribeSecurityGroupsInput); ok {
		return x.Ec2_DescribeSecurityGroupsInput
	}
	return nil
}

func (m *BezosRequest) GetEc2_DescribeSubnetsInput() *opsee_aws_ec2.DescribeSubnetsInput {
	if x, ok := m.GetInput().(*BezosRequest_Ec2_DescribeSubnetsInput); ok {
		return x.Ec2_DescribeSubnetsInput
	}
	return nil
}

func (m *BezosRequest) GetEc2_DescribeVpcsInput() *opsee_aws_ec2.DescribeVpcsInput {
	if x, ok := m.GetInput().(*BezosRequest_Ec2_DescribeVpcsInput); ok {
		return x.Ec2_DescribeVpcsInput
	}
	return nil
}

func (m *BezosRequest) GetEc2_DescribeRouteTablesInput() *opsee_aws_ec2.DescribeRouteTablesInput {
	if x, ok := m.GetInput().(*BezosRequest_Ec2_DescribeRouteTablesInput); ok {
		return x.Ec2_DescribeRouteTablesInput
	}
	return nil
}

func (m *BezosRequest) GetElb_DescribeLoadBalancersInput() *opsee_aws_elb.DescribeLoadBalancersInput {
	if x, ok := m.GetInput().(*BezosRequest_Elb_DescribeLoadBalancersInput); ok {
		return x.Elb_DescribeLoadBalancersInput
	}
	return nil
}

func (m *BezosRequest) GetAutoscaling_DescribeAutoScalingGroupsInput() *opsee_aws_autoscaling.DescribeAutoScalingGroupsInput {
	if x, ok := m.GetInput().(*BezosRequest_Autoscaling_DescribeAutoScalingGroupsInput); ok {
		return x.Autoscaling_DescribeAutoScalingGroupsInput
	}
	return nil
}

func (m *BezosRequest) GetRds_DescribeDBInstancesInput() *opsee_aws_rds.DescribeDBInstancesInput {
	if x, ok := m.GetInput().(*BezosRequest_Rds_DescribeDBInstancesInput); ok {
		return x.Rds_DescribeDBInstancesInput
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*BezosRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), []interface{}) {
	return _BezosRequest_OneofMarshaler, _BezosRequest_OneofUnmarshaler, []interface{}{
		(*BezosRequest_Cloudwatch_ListMetricsInput)(nil),
		(*BezosRequest_Cloudwatch_GetMetricsStatisticsInput)(nil),
		(*BezosRequest_Ec2_DescribeInstancesInput)(nil),
		(*BezosRequest_Ec2_DescribeSecurityGroupsInput)(nil),
		(*BezosRequest_Ec2_DescribeSubnetsInput)(nil),
		(*BezosRequest_Ec2_DescribeVpcsInput)(nil),
		(*BezosRequest_Ec2_DescribeRouteTablesInput)(nil),
		(*BezosRequest_Elb_DescribeLoadBalancersInput)(nil),
		(*BezosRequest_Autoscaling_DescribeAutoScalingGroupsInput)(nil),
		(*BezosRequest_Rds_DescribeDBInstancesInput)(nil),
	}
}

func _BezosRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*BezosRequest)
	// input
	switch x := m.Input.(type) {
	case *BezosRequest_Cloudwatch_ListMetricsInput:
		_ = b.EncodeVarint(101<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Cloudwatch_ListMetricsInput); err != nil {
			return err
		}
	case *BezosRequest_Cloudwatch_GetMetricsStatisticsInput:
		_ = b.EncodeVarint(102<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Cloudwatch_GetMetricsStatisticsInput); err != nil {
			return err
		}
	case *BezosRequest_Ec2_DescribeInstancesInput:
		_ = b.EncodeVarint(201<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ec2_DescribeInstancesInput); err != nil {
			return err
		}
	case *BezosRequest_Ec2_DescribeSecurityGroupsInput:
		_ = b.EncodeVarint(202<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ec2_DescribeSecurityGroupsInput); err != nil {
			return err
		}
	case *BezosRequest_Ec2_DescribeSubnetsInput:
		_ = b.EncodeVarint(203<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ec2_DescribeSubnetsInput); err != nil {
			return err
		}
	case *BezosRequest_Ec2_DescribeVpcsInput:
		_ = b.EncodeVarint(204<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ec2_DescribeVpcsInput); err != nil {
			return err
		}
	case *BezosRequest_Ec2_DescribeRouteTablesInput:
		_ = b.EncodeVarint(205<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ec2_DescribeRouteTablesInput); err != nil {
			return err
		}
	case *BezosRequest_Elb_DescribeLoadBalancersInput:
		_ = b.EncodeVarint(301<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Elb_DescribeLoadBalancersInput); err != nil {
			return err
		}
	case *BezosRequest_Autoscaling_DescribeAutoScalingGroupsInput:
		_ = b.EncodeVarint(401<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Autoscaling_DescribeAutoScalingGroupsInput); err != nil {
			return err
		}
	case *BezosRequest_Rds_DescribeDBInstancesInput:
		_ = b.EncodeVarint(501<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Rds_DescribeDBInstancesInput); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("BezosRequest.Input has unexpected type %T", x)
	}
	return nil
}

func _BezosRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*BezosRequest)
	switch tag {
	case 101: // input.cloudwatch_ListMetricsInput
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(opsee_aws_cloudwatch.ListMetricsInput)
		err := b.DecodeMessage(msg)
		m.Input = &BezosRequest_Cloudwatch_ListMetricsInput{msg}
		return true, err
	case 102: // input.cloudwatch_GetMetricsStatisticsInput
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(opsee_aws_cloudwatch.GetMetricStatisticsInput)
		err := b.DecodeMessage(msg)
		m.Input = &BezosRequest_Cloudwatch_GetMetricsStatisticsInput{msg}
		return true, err
	case 201: // input.ec2_DescribeInstancesInput
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(opsee_aws_ec2.DescribeInstancesInput)
		err := b.DecodeMessage(msg)
		m.Input = &BezosRequest_Ec2_DescribeInstancesInput{msg}
		return true, err
	case 202: // input.ec2_DescribeSecurityGroupsInput
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(opsee_aws_ec2.DescribeSecurityGroupsInput)
		err := b.DecodeMessage(msg)
		m.Input = &BezosRequest_Ec2_DescribeSecurityGroupsInput{msg}
		return true, err
	case 203: // input.ec2_DescribeSubnetsInput
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(opsee_aws_ec2.DescribeSubnetsInput)
		err := b.DecodeMessage(msg)
		m.Input = &BezosRequest_Ec2_DescribeSubnetsInput{msg}
		return true, err
	case 204: // input.ec2_DescribeVpcsInput
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(opsee_aws_ec2.DescribeVpcsInput)
		err := b.DecodeMessage(msg)
		m.Input = &BezosRequest_Ec2_DescribeVpcsInput{msg}
		return true, err
	case 205: // input.ec2_DescribeRouteTablesInput
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(opsee_aws_ec2.DescribeRouteTablesInput)
		err := b.DecodeMessage(msg)
		m.Input = &BezosRequest_Ec2_DescribeRouteTablesInput{msg}
		return true, err
	case 301: // input.elb_DescribeLoadBalancersInput
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(opsee_aws_elb.DescribeLoadBalancersInput)
		err := b.DecodeMessage(msg)
		m.Input = &BezosRequest_Elb_DescribeLoadBalancersInput{msg}
		return true, err
	case 401: // input.autoscaling_DescribeAutoScalingGroupsInput
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(opsee_aws_autoscaling.DescribeAutoScalingGroupsInput)
		err := b.DecodeMessage(msg)
		m.Input = &BezosRequest_Autoscaling_DescribeAutoScalingGroupsInput{msg}
		return true, err
	case 501: // input.rds_DescribeDBInstancesInput
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(opsee_aws_rds.DescribeDBInstancesInput)
		err := b.DecodeMessage(msg)
		m.Input = &BezosRequest_Rds_DescribeDBInstancesInput{msg}
		return true, err
	default:
		return false, nil
	}
}

func init() {
	proto.RegisterType((*BezosRequest)(nil), "opsee.BezosRequest")
}
func (this *BezosRequest) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*BezosRequest)
	if !ok {
		that2, ok := that.(BezosRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.User.Equal(that1.User) {
		return false
	}
	if that1.Input == nil {
		if this.Input != nil {
			return false
		}
	} else if this.Input == nil {
		return false
	} else if !this.Input.Equal(that1.Input) {
		return false
	}
	return true
}
func (this *BezosRequest_Cloudwatch_ListMetricsInput) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*BezosRequest_Cloudwatch_ListMetricsInput)
	if !ok {
		that2, ok := that.(BezosRequest_Cloudwatch_ListMetricsInput)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Cloudwatch_ListMetricsInput.Equal(that1.Cloudwatch_ListMetricsInput) {
		return false
	}
	return true
}
func (this *BezosRequest_Cloudwatch_GetMetricsStatisticsInput) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*BezosRequest_Cloudwatch_GetMetricsStatisticsInput)
	if !ok {
		that2, ok := that.(BezosRequest_Cloudwatch_GetMetricsStatisticsInput)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Cloudwatch_GetMetricsStatisticsInput.Equal(that1.Cloudwatch_GetMetricsStatisticsInput) {
		return false
	}
	return true
}
func (this *BezosRequest_Ec2_DescribeInstancesInput) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*BezosRequest_Ec2_DescribeInstancesInput)
	if !ok {
		that2, ok := that.(BezosRequest_Ec2_DescribeInstancesInput)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Ec2_DescribeInstancesInput.Equal(that1.Ec2_DescribeInstancesInput) {
		return false
	}
	return true
}
func (this *BezosRequest_Ec2_DescribeSecurityGroupsInput) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*BezosRequest_Ec2_DescribeSecurityGroupsInput)
	if !ok {
		that2, ok := that.(BezosRequest_Ec2_DescribeSecurityGroupsInput)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Ec2_DescribeSecurityGroupsInput.Equal(that1.Ec2_DescribeSecurityGroupsInput) {
		return false
	}
	return true
}
func (this *BezosRequest_Ec2_DescribeSubnetsInput) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*BezosRequest_Ec2_DescribeSubnetsInput)
	if !ok {
		that2, ok := that.(BezosRequest_Ec2_DescribeSubnetsInput)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Ec2_DescribeSubnetsInput.Equal(that1.Ec2_DescribeSubnetsInput) {
		return false
	}
	return true
}
func (this *BezosRequest_Ec2_DescribeVpcsInput) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*BezosRequest_Ec2_DescribeVpcsInput)
	if !ok {
		that2, ok := that.(BezosRequest_Ec2_DescribeVpcsInput)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Ec2_DescribeVpcsInput.Equal(that1.Ec2_DescribeVpcsInput) {
		return false
	}
	return true
}
func (this *BezosRequest_Ec2_DescribeRouteTablesInput) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*BezosRequest_Ec2_DescribeRouteTablesInput)
	if !ok {
		that2, ok := that.(BezosRequest_Ec2_DescribeRouteTablesInput)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Ec2_DescribeRouteTablesInput.Equal(that1.Ec2_DescribeRouteTablesInput) {
		return false
	}
	return true
}
func (this *BezosRequest_Elb_DescribeLoadBalancersInput) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*BezosRequest_Elb_DescribeLoadBalancersInput)
	if !ok {
		that2, ok := that.(BezosRequest_Elb_DescribeLoadBalancersInput)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Elb_DescribeLoadBalancersInput.Equal(that1.Elb_DescribeLoadBalancersInput) {
		return false
	}
	return true
}
func (this *BezosRequest_Autoscaling_DescribeAutoScalingGroupsInput) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*BezosRequest_Autoscaling_DescribeAutoScalingGroupsInput)
	if !ok {
		that2, ok := that.(BezosRequest_Autoscaling_DescribeAutoScalingGroupsInput)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Autoscaling_DescribeAutoScalingGroupsInput.Equal(that1.Autoscaling_DescribeAutoScalingGroupsInput) {
		return false
	}
	return true
}
func (this *BezosRequest_Rds_DescribeDBInstancesInput) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*BezosRequest_Rds_DescribeDBInstancesInput)
	if !ok {
		that2, ok := that.(BezosRequest_Rds_DescribeDBInstancesInput)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.Rds_DescribeDBInstancesInput.Equal(that1.Rds_DescribeDBInstancesInput) {
		return false
	}
	return true
}

type BezosRequestGetter interface {
	GetBezosRequest() *BezosRequest
}

var GraphQLBezosRequestType *github_com_graphql_go_graphql.Object
var GraphQLBezosRequestInputUnion *github_com_graphql_go_graphql.Union

func (g *BezosRequest_Cloudwatch_ListMetricsInput) GetListMetricsInput() *opsee_aws_cloudwatch.ListMetricsInput {
	return g.Cloudwatch_ListMetricsInput
}
func (g *BezosRequest_Cloudwatch_GetMetricsStatisticsInput) GetGetMetricStatisticsInput() *opsee_aws_cloudwatch.GetMetricStatisticsInput {
	return g.Cloudwatch_GetMetricsStatisticsInput
}
func (g *BezosRequest_Ec2_DescribeInstancesInput) GetDescribeInstancesInput() *opsee_aws_ec2.DescribeInstancesInput {
	return g.Ec2_DescribeInstancesInput
}
func (g *BezosRequest_Ec2_DescribeSecurityGroupsInput) GetDescribeSecurityGroupsInput() *opsee_aws_ec2.DescribeSecurityGroupsInput {
	return g.Ec2_DescribeSecurityGroupsInput
}
func (g *BezosRequest_Ec2_DescribeSubnetsInput) GetDescribeSubnetsInput() *opsee_aws_ec2.DescribeSubnetsInput {
	return g.Ec2_DescribeSubnetsInput
}
func (g *BezosRequest_Ec2_DescribeVpcsInput) GetDescribeVpcsInput() *opsee_aws_ec2.DescribeVpcsInput {
	return g.Ec2_DescribeVpcsInput
}
func (g *BezosRequest_Ec2_DescribeRouteTablesInput) GetDescribeRouteTablesInput() *opsee_aws_ec2.DescribeRouteTablesInput {
	return g.Ec2_DescribeRouteTablesInput
}
func (g *BezosRequest_Elb_DescribeLoadBalancersInput) GetDescribeLoadBalancersInput() *opsee_aws_elb.DescribeLoadBalancersInput {
	return g.Elb_DescribeLoadBalancersInput
}
func (g *BezosRequest_Autoscaling_DescribeAutoScalingGroupsInput) GetDescribeAutoScalingGroupsInput() *opsee_aws_autoscaling.DescribeAutoScalingGroupsInput {
	return g.Autoscaling_DescribeAutoScalingGroupsInput
}
func (g *BezosRequest_Rds_DescribeDBInstancesInput) GetDescribeDBInstancesInput() *opsee_aws_rds.DescribeDBInstancesInput {
	return g.Rds_DescribeDBInstancesInput
}

func init() {
	GraphQLBezosRequestType = github_com_graphql_go_graphql.NewObject(github_com_graphql_go_graphql.ObjectConfig{
		Name:        "serviceBezosRequest",
		Description: "",
		Fields: (github_com_graphql_go_graphql.FieldsThunk)(func() github_com_graphql_go_graphql.Fields {
			return github_com_graphql_go_graphql.Fields{
				"user": &github_com_graphql_go_graphql.Field{
					Type:        opsee1.GraphQLUserType,
					Description: "",
					Resolve: func(p github_com_graphql_go_graphql.ResolveParams) (interface{}, error) {
						obj, ok := p.Source.(*BezosRequest)
						if ok {
							if obj.User == nil {
								return nil, nil
							}
							return obj.GetUser(), nil
						}
						inter, ok := p.Source.(BezosRequestGetter)
						if ok {
							face := inter.GetBezosRequest()
							if face == nil {
								return nil, nil
							}
							if face.User == nil {
								return nil, nil
							}
							return face.GetUser(), nil
						}
						return nil, fmt.Errorf("field user not resolved")
					},
				},
				"input": &github_com_graphql_go_graphql.Field{
					Type:        GraphQLBezosRequestInputUnion,
					Description: "",
					Resolve: func(p github_com_graphql_go_graphql.ResolveParams) (interface{}, error) {
						obj, ok := p.Source.(*BezosRequest)
						if !ok {
							return nil, fmt.Errorf("field input not resolved")
						}
						return obj.GetInput(), nil
					},
				},
			}
		}),
	})
	GraphQLBezosRequestInputUnion = github_com_graphql_go_graphql.NewUnion(github_com_graphql_go_graphql.UnionConfig{
		Name:        "BezosRequestInput",
		Description: "",
		Types: []*github_com_graphql_go_graphql.Object{
			opsee_aws_cloudwatch.GraphQLListMetricsInputType,
			opsee_aws_cloudwatch.GraphQLGetMetricStatisticsInputType,
			opsee_aws_ec2.GraphQLDescribeInstancesInputType,
			opsee_aws_ec2.GraphQLDescribeSecurityGroupsInputType,
			opsee_aws_ec2.GraphQLDescribeSubnetsInputType,
			opsee_aws_ec2.GraphQLDescribeVpcsInputType,
			opsee_aws_ec2.GraphQLDescribeRouteTablesInputType,
			opsee_aws_elb.GraphQLDescribeLoadBalancersInputType,
			opsee_aws_autoscaling.GraphQLDescribeAutoScalingGroupsInputType,
			opsee_aws_rds.GraphQLDescribeDBInstancesInputType,
		},
		ResolveType: func(value interface{}, info github_com_graphql_go_graphql.ResolveInfo) *github_com_graphql_go_graphql.Object {
			switch value.(type) {
			case *BezosRequest_Cloudwatch_ListMetricsInput:
				return opsee_aws_cloudwatch.GraphQLListMetricsInputType
			case *BezosRequest_Cloudwatch_GetMetricsStatisticsInput:
				return opsee_aws_cloudwatch.GraphQLGetMetricStatisticsInputType
			case *BezosRequest_Ec2_DescribeInstancesInput:
				return opsee_aws_ec2.GraphQLDescribeInstancesInputType
			case *BezosRequest_Ec2_DescribeSecurityGroupsInput:
				return opsee_aws_ec2.GraphQLDescribeSecurityGroupsInputType
			case *BezosRequest_Ec2_DescribeSubnetsInput:
				return opsee_aws_ec2.GraphQLDescribeSubnetsInputType
			case *BezosRequest_Ec2_DescribeVpcsInput:
				return opsee_aws_ec2.GraphQLDescribeVpcsInputType
			case *BezosRequest_Ec2_DescribeRouteTablesInput:
				return opsee_aws_ec2.GraphQLDescribeRouteTablesInputType
			case *BezosRequest_Elb_DescribeLoadBalancersInput:
				return opsee_aws_elb.GraphQLDescribeLoadBalancersInputType
			case *BezosRequest_Autoscaling_DescribeAutoScalingGroupsInput:
				return opsee_aws_autoscaling.GraphQLDescribeAutoScalingGroupsInputType
			case *BezosRequest_Rds_DescribeDBInstancesInput:
				return opsee_aws_rds.GraphQLDescribeDBInstancesInputType
			}
			return nil
		},
	})
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for Bezos service

type BezosClient interface {
	CloudwatchListMetrics(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_cloudwatch.ListMetricsOutput, error)
	CloudwatchGetMetricStatistics(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_cloudwatch.GetMetricStatisticsOutput, error)
	EC2DescribeInstances(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_ec2.DescribeInstancesOutput, error)
	EC2DescribeSecurityGroups(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_ec2.DescribeSecurityGroupsOutput, error)
	EC2DescribeSubnets(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_ec2.DescribeSubnetsOutput, error)
	EC2DescribeVpcs(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_ec2.DescribeVpcsOutput, error)
	EC2DescribeRouteTables(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_ec2.DescribeRouteTablesOutput, error)
	ELBDescribeLoadBalancers(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_elb.DescribeLoadBalancersOutput, error)
	AutoScalingDescribeAutoScalingGroups(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_autoscaling.DescribeAutoScalingGroupsOutput, error)
	RDSDescribeDBInstances(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_rds.DescribeDBInstancesOutput, error)
}

type bezosClient struct {
	cc *grpc.ClientConn
}

func NewBezosClient(cc *grpc.ClientConn) BezosClient {
	return &bezosClient{cc}
}

func (c *bezosClient) CloudwatchListMetrics(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_cloudwatch.ListMetricsOutput, error) {
	out := new(opsee_aws_cloudwatch.ListMetricsOutput)
	err := grpc.Invoke(ctx, "/opsee.Bezos/CloudwatchListMetrics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bezosClient) CloudwatchGetMetricStatistics(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_cloudwatch.GetMetricStatisticsOutput, error) {
	out := new(opsee_aws_cloudwatch.GetMetricStatisticsOutput)
	err := grpc.Invoke(ctx, "/opsee.Bezos/CloudwatchGetMetricStatistics", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bezosClient) EC2DescribeInstances(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_ec2.DescribeInstancesOutput, error) {
	out := new(opsee_aws_ec2.DescribeInstancesOutput)
	err := grpc.Invoke(ctx, "/opsee.Bezos/EC2DescribeInstances", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bezosClient) EC2DescribeSecurityGroups(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_ec2.DescribeSecurityGroupsOutput, error) {
	out := new(opsee_aws_ec2.DescribeSecurityGroupsOutput)
	err := grpc.Invoke(ctx, "/opsee.Bezos/EC2DescribeSecurityGroups", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bezosClient) EC2DescribeSubnets(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_ec2.DescribeSubnetsOutput, error) {
	out := new(opsee_aws_ec2.DescribeSubnetsOutput)
	err := grpc.Invoke(ctx, "/opsee.Bezos/EC2DescribeSubnets", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bezosClient) EC2DescribeVpcs(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_ec2.DescribeVpcsOutput, error) {
	out := new(opsee_aws_ec2.DescribeVpcsOutput)
	err := grpc.Invoke(ctx, "/opsee.Bezos/EC2DescribeVpcs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bezosClient) EC2DescribeRouteTables(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_ec2.DescribeRouteTablesOutput, error) {
	out := new(opsee_aws_ec2.DescribeRouteTablesOutput)
	err := grpc.Invoke(ctx, "/opsee.Bezos/EC2DescribeRouteTables", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bezosClient) ELBDescribeLoadBalancers(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_elb.DescribeLoadBalancersOutput, error) {
	out := new(opsee_aws_elb.DescribeLoadBalancersOutput)
	err := grpc.Invoke(ctx, "/opsee.Bezos/ELBDescribeLoadBalancers", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bezosClient) AutoScalingDescribeAutoScalingGroups(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_autoscaling.DescribeAutoScalingGroupsOutput, error) {
	out := new(opsee_aws_autoscaling.DescribeAutoScalingGroupsOutput)
	err := grpc.Invoke(ctx, "/opsee.Bezos/AutoScalingDescribeAutoScalingGroups", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bezosClient) RDSDescribeDBInstances(ctx context.Context, in *BezosRequest, opts ...grpc.CallOption) (*opsee_aws_rds.DescribeDBInstancesOutput, error) {
	out := new(opsee_aws_rds.DescribeDBInstancesOutput)
	err := grpc.Invoke(ctx, "/opsee.Bezos/RDSDescribeDBInstances", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Bezos service

type BezosServer interface {
	CloudwatchListMetrics(context.Context, *BezosRequest) (*opsee_aws_cloudwatch.ListMetricsOutput, error)
	CloudwatchGetMetricStatistics(context.Context, *BezosRequest) (*opsee_aws_cloudwatch.GetMetricStatisticsOutput, error)
	EC2DescribeInstances(context.Context, *BezosRequest) (*opsee_aws_ec2.DescribeInstancesOutput, error)
	EC2DescribeSecurityGroups(context.Context, *BezosRequest) (*opsee_aws_ec2.DescribeSecurityGroupsOutput, error)
	EC2DescribeSubnets(context.Context, *BezosRequest) (*opsee_aws_ec2.DescribeSubnetsOutput, error)
	EC2DescribeVpcs(context.Context, *BezosRequest) (*opsee_aws_ec2.DescribeVpcsOutput, error)
	EC2DescribeRouteTables(context.Context, *BezosRequest) (*opsee_aws_ec2.DescribeRouteTablesOutput, error)
	ELBDescribeLoadBalancers(context.Context, *BezosRequest) (*opsee_aws_elb.DescribeLoadBalancersOutput, error)
	AutoScalingDescribeAutoScalingGroups(context.Context, *BezosRequest) (*opsee_aws_autoscaling.DescribeAutoScalingGroupsOutput, error)
	RDSDescribeDBInstances(context.Context, *BezosRequest) (*opsee_aws_rds.DescribeDBInstancesOutput, error)
}

func RegisterBezosServer(s *grpc.Server, srv BezosServer) {
	s.RegisterService(&_Bezos_serviceDesc, srv)
}

func _Bezos_CloudwatchListMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(BezosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BezosServer).CloudwatchListMetrics(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bezos_CloudwatchGetMetricStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(BezosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BezosServer).CloudwatchGetMetricStatistics(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bezos_EC2DescribeInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(BezosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BezosServer).EC2DescribeInstances(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bezos_EC2DescribeSecurityGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(BezosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BezosServer).EC2DescribeSecurityGroups(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bezos_EC2DescribeSubnets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(BezosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BezosServer).EC2DescribeSubnets(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bezos_EC2DescribeVpcs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(BezosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BezosServer).EC2DescribeVpcs(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bezos_EC2DescribeRouteTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(BezosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BezosServer).EC2DescribeRouteTables(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bezos_ELBDescribeLoadBalancers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(BezosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BezosServer).ELBDescribeLoadBalancers(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bezos_AutoScalingDescribeAutoScalingGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(BezosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BezosServer).AutoScalingDescribeAutoScalingGroups(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _Bezos_RDSDescribeDBInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(BezosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(BezosServer).RDSDescribeDBInstances(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _Bezos_serviceDesc = grpc.ServiceDesc{
	ServiceName: "opsee.Bezos",
	HandlerType: (*BezosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CloudwatchListMetrics",
			Handler:    _Bezos_CloudwatchListMetrics_Handler,
		},
		{
			MethodName: "CloudwatchGetMetricStatistics",
			Handler:    _Bezos_CloudwatchGetMetricStatistics_Handler,
		},
		{
			MethodName: "EC2DescribeInstances",
			Handler:    _Bezos_EC2DescribeInstances_Handler,
		},
		{
			MethodName: "EC2DescribeSecurityGroups",
			Handler:    _Bezos_EC2DescribeSecurityGroups_Handler,
		},
		{
			MethodName: "EC2DescribeSubnets",
			Handler:    _Bezos_EC2DescribeSubnets_Handler,
		},
		{
			MethodName: "EC2DescribeVpcs",
			Handler:    _Bezos_EC2DescribeVpcs_Handler,
		},
		{
			MethodName: "EC2DescribeRouteTables",
			Handler:    _Bezos_EC2DescribeRouteTables_Handler,
		},
		{
			MethodName: "ELBDescribeLoadBalancers",
			Handler:    _Bezos_ELBDescribeLoadBalancers_Handler,
		},
		{
			MethodName: "AutoScalingDescribeAutoScalingGroups",
			Handler:    _Bezos_AutoScalingDescribeAutoScalingGroups_Handler,
		},
		{
			MethodName: "RDSDescribeDBInstances",
			Handler:    _Bezos_RDSDescribeDBInstances_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

func NewPopulatedBezosRequest(r randyBezos, easy bool) *BezosRequest {
	this := &BezosRequest{}
	if r.Intn(10) != 0 {
		this.User = opsee1.NewPopulatedUser(r, easy)
	}
	oneofNumber_Input := []int32{101, 102, 201, 202, 203, 204, 205, 301, 401, 501}[r.Intn(10)]
	switch oneofNumber_Input {
	case 101:
		this.Input = NewPopulatedBezosRequest_Cloudwatch_ListMetricsInput(r, easy)
	case 102:
		this.Input = NewPopulatedBezosRequest_Cloudwatch_GetMetricsStatisticsInput(r, easy)
	case 201:
		this.Input = NewPopulatedBezosRequest_Ec2_DescribeInstancesInput(r, easy)
	case 202:
		this.Input = NewPopulatedBezosRequest_Ec2_DescribeSecurityGroupsInput(r, easy)
	case 203:
		this.Input = NewPopulatedBezosRequest_Ec2_DescribeSubnetsInput(r, easy)
	case 204:
		this.Input = NewPopulatedBezosRequest_Ec2_DescribeVpcsInput(r, easy)
	case 205:
		this.Input = NewPopulatedBezosRequest_Ec2_DescribeRouteTablesInput(r, easy)
	case 301:
		this.Input = NewPopulatedBezosRequest_Elb_DescribeLoadBalancersInput(r, easy)
	case 401:
		this.Input = NewPopulatedBezosRequest_Autoscaling_DescribeAutoScalingGroupsInput(r, easy)
	case 501:
		this.Input = NewPopulatedBezosRequest_Rds_DescribeDBInstancesInput(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedBezosRequest_Cloudwatch_ListMetricsInput(r randyBezos, easy bool) *BezosRequest_Cloudwatch_ListMetricsInput {
	this := &BezosRequest_Cloudwatch_ListMetricsInput{}
	this.Cloudwatch_ListMetricsInput = opsee_aws_cloudwatch.NewPopulatedListMetricsInput(r, easy)
	return this
}
func NewPopulatedBezosRequest_Cloudwatch_GetMetricsStatisticsInput(r randyBezos, easy bool) *BezosRequest_Cloudwatch_GetMetricsStatisticsInput {
	this := &BezosRequest_Cloudwatch_GetMetricsStatisticsInput{}
	this.Cloudwatch_GetMetricsStatisticsInput = opsee_aws_cloudwatch.NewPopulatedGetMetricStatisticsInput(r, easy)
	return this
}
func NewPopulatedBezosRequest_Ec2_DescribeInstancesInput(r randyBezos, easy bool) *BezosRequest_Ec2_DescribeInstancesInput {
	this := &BezosRequest_Ec2_DescribeInstancesInput{}
	this.Ec2_DescribeInstancesInput = opsee_aws_ec2.NewPopulatedDescribeInstancesInput(r, easy)
	return this
}
func NewPopulatedBezosRequest_Ec2_DescribeSecurityGroupsInput(r randyBezos, easy bool) *BezosRequest_Ec2_DescribeSecurityGroupsInput {
	this := &BezosRequest_Ec2_DescribeSecurityGroupsInput{}
	this.Ec2_DescribeSecurityGroupsInput = opsee_aws_ec2.NewPopulatedDescribeSecurityGroupsInput(r, easy)
	return this
}
func NewPopulatedBezosRequest_Ec2_DescribeSubnetsInput(r randyBezos, easy bool) *BezosRequest_Ec2_DescribeSubnetsInput {
	this := &BezosRequest_Ec2_DescribeSubnetsInput{}
	this.Ec2_DescribeSubnetsInput = opsee_aws_ec2.NewPopulatedDescribeSubnetsInput(r, easy)
	return this
}
func NewPopulatedBezosRequest_Ec2_DescribeVpcsInput(r randyBezos, easy bool) *BezosRequest_Ec2_DescribeVpcsInput {
	this := &BezosRequest_Ec2_DescribeVpcsInput{}
	this.Ec2_DescribeVpcsInput = opsee_aws_ec2.NewPopulatedDescribeVpcsInput(r, easy)
	return this
}
func NewPopulatedBezosRequest_Ec2_DescribeRouteTablesInput(r randyBezos, easy bool) *BezosRequest_Ec2_DescribeRouteTablesInput {
	this := &BezosRequest_Ec2_DescribeRouteTablesInput{}
	this.Ec2_DescribeRouteTablesInput = opsee_aws_ec2.NewPopulatedDescribeRouteTablesInput(r, easy)
	return this
}
func NewPopulatedBezosRequest_Elb_DescribeLoadBalancersInput(r randyBezos, easy bool) *BezosRequest_Elb_DescribeLoadBalancersInput {
	this := &BezosRequest_Elb_DescribeLoadBalancersInput{}
	this.Elb_DescribeLoadBalancersInput = opsee_aws_elb.NewPopulatedDescribeLoadBalancersInput(r, easy)
	return this
}
func NewPopulatedBezosRequest_Autoscaling_DescribeAutoScalingGroupsInput(r randyBezos, easy bool) *BezosRequest_Autoscaling_DescribeAutoScalingGroupsInput {
	this := &BezosRequest_Autoscaling_DescribeAutoScalingGroupsInput{}
	this.Autoscaling_DescribeAutoScalingGroupsInput = opsee_aws_autoscaling.NewPopulatedDescribeAutoScalingGroupsInput(r, easy)
	return this
}
func NewPopulatedBezosRequest_Rds_DescribeDBInstancesInput(r randyBezos, easy bool) *BezosRequest_Rds_DescribeDBInstancesInput {
	this := &BezosRequest_Rds_DescribeDBInstancesInput{}
	this.Rds_DescribeDBInstancesInput = opsee_aws_rds.NewPopulatedDescribeDBInstancesInput(r, easy)
	return this
}

type randyBezos interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneBezos(r randyBezos) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringBezos(r randyBezos) string {
	v1 := r.Intn(100)
	tmps := make([]rune, v1)
	for i := 0; i < v1; i++ {
		tmps[i] = randUTF8RuneBezos(r)
	}
	return string(tmps)
}
func randUnrecognizedBezos(r randyBezos, maxFieldNumber int) (data []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		data = randFieldBezos(data, r, fieldNumber, wire)
	}
	return data
}
func randFieldBezos(data []byte, r randyBezos, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		data = encodeVarintPopulateBezos(data, uint64(key))
		v2 := r.Int63()
		if r.Intn(2) == 0 {
			v2 *= -1
		}
		data = encodeVarintPopulateBezos(data, uint64(v2))
	case 1:
		data = encodeVarintPopulateBezos(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		data = encodeVarintPopulateBezos(data, uint64(key))
		ll := r.Intn(100)
		data = encodeVarintPopulateBezos(data, uint64(ll))
		for j := 0; j < ll; j++ {
			data = append(data, byte(r.Intn(256)))
		}
	default:
		data = encodeVarintPopulateBezos(data, uint64(key))
		data = append(data, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return data
}
func encodeVarintPopulateBezos(data []byte, v uint64) []byte {
	for v >= 1<<7 {
		data = append(data, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	data = append(data, uint8(v))
	return data
}
